import dns from 'node:dns';
dns.setServers(['8.8.8.8', '1.1.1.1']);

import dotenv from 'dotenv';
import mongoose from 'mongoose';
import Location from './models/Location.js';

dotenv.config();

const MONGODB_URI = process.env.MONGODB_URI;

if (!MONGODB_URI) {
  console.log(JSON.stringify({ error: 'MONGODB_URI missing from .env' }));
  process.exit(1);
}

// Complete Administrative Dataset of India: 36 States & UTs, 780+ Official Districts, Real Villages/Tehsils
const INDIA_ADMINISTRATIVE_DATA = {
  // --- 28 STATES ---
  "Andhra Pradesh": {
    "Alluri Sitharama Raju": ["Paderu", "Araku Valley", "Rampachodavaram", "Chintoor"],
    "Anakapalli": ["Anakapalle", "Chodavaram", "Elamanchili", "Narsipatnam"],
    "Ananthapuramu": ["Anantapur", "Dharmavaram", "Guntakal", "Tadipatri", "Kalyandurg"],
    "Annamayya": ["Rayachoti", "Rajampet", "Madanapalle", "Railway Koduru"],
    "Bapatla": ["Bapatla", "Repalle", "Vemuru", "Parchur"],
    "Chittoor": ["Chittoor", "Nagari", "Palamaner", "Punganur", "Gudipala"],
    "East Godavari": ["Rajahmundry", "Kovvur", "Nidadavole", "Anaparthi"],
    "Eluru": ["Eluru", "Jangareddygudem", "Nuzvid", "Chintalapudi"],
    "Guntur": ["Guntur", "Tenali", "Mangalagiri", "Ponnur", "Tadikonda"],
    "Kakinada": ["Kakinada", "Pithapuram", "Tuni", "Peddapuram", "Samalkot"],
    "Kurnool": ["Kurnool", "Adoni", "Yemmiganur", "Pattikonda", "Kodumur"],
    "Nandyal": ["Nandyal", "Dhone", "Allagadda", "Nandikotkur", "Banaganapalle"],
    "NTR": ["Vijayawada", "Jaggayyapeta", "Nandigama", "Tiruvuru"],
    "Palnadu": ["Narasaraopet", "Gurazala", "Sattenapalle", "Vinukonda"],
    "Parvathipuram Manyam": ["Parvathipuram", "Palakonda", "Salur", "Kurupam"],
    "Prakasam": ["Ongole", "Chirala", "Markapur", "Giddalur", "Kanigiri"],
    "Sri Potti Sriramulu Nellore": ["Nellore", "Kavali", "Gudur", "Atmakur", "Kovur"],
    "Sri Sathya Sai": ["Puttaparthi", "Kadiri", "Hindupur", "Penukonda"],
    "Srikakulam": ["Srikakulam", "Tekkali", "Palasa", "Amadalavalasa", "Narasannapeta"],
    "Tirupati": ["Tirupati", "Srikalahasti", "Sullurpeta", "Venkatagiri"],
    "Visakhapatnam": ["Visakhapatnam", "Gajuwaka", "Bheemunipatnam", "Pendurthi"],
    "Vizianagaram": ["Vizianagaram", "Bobbili", "Cheepurupalli", "Gajapathinagaram"],
    "West Godavari": ["Bhimavaram", "Tadepalligudem", "Narsapuram", "Tanuku"],
    "YSR Kadapa": ["Kadapa", "Proddatur", "Jammalamadugu", "Badvel", "Pulivendula"]
  },
  "Arunachal Pradesh": {
    "Anjaw": ["Hawai", "Hayuliang", "Manchal", "Goiliang"],
    "Changlang": ["Changlang", "Miao", "Jairampur", "Bordumsa"],
    "East Kameng": ["Seppa", "Chayang Tajo", "Bameng", "Pakke Kessang"],
    "East Siang": ["Pasighat", "Mebo", "Ruksin", "Sille-Oyan"],
    "Kamle": ["Raga", "Dollungmukh", "Puchigeko", "Geba"],
    "Kra Daadi": ["Palin", "Nyapin", "Chambang", "Tali"],
    "Kurung Kumey": ["Koloriang", "Sangram", "Nyapin", "Parsiparlo"],
    "Lepa Rada": ["Basar", "Tirbin", "Daring", "Sago"],
    "Lhit": ["Tezu", "Sunpura", "Wakro", "Chowkham"],
    "Longding": ["Longding", "Kanubari", "Pangchao", "Wakka"],
    "Lower Dibang Valley": ["Roing", "Dambuk", "Desali", "Hunli"],
    "Lower Subansiri": ["Ziro", "Yachuli", "Yazali", "Pistana"],
    "Namsai": ["Namsai", "Chowkham", "Lathao", "Mahadevpur"],
    "Pakke Kessang": ["Lemmi", "Pakke Kessang", "Seijosa", "Passa Valley"],
    "Papum Pare": ["Yupia", "Itanagar", "Naharlagun", "Doimukh", "Sagalee"],
    "Shi Yomi": ["Tato", "Mechuka", "Pidi", "Monigong"],
    "Siang": ["Pangin", "Boleng", "Rumgong", "Kaying"],
    "Tawang": ["Tawang", "Jang", "Lumla", "Kitpi"],
    "Tirap": ["Khonsa", "Deomali", "Laju", "Soha"],
    "Upper Dibang Valley": ["Anini", "Mipi", "Etalin", "Anelho"],
    "Upper Siang": ["Yingkiong", "Tuting", "Geku", "Mariyang"],
    "Upper Subansiri": ["Daporijo", "Dumporijo", "Taliha", "Nacho"],
    "West Kameng": ["Bomdila", "Dirang", "Rupa", "Singchung", "Kalaktang"],
    "West Siang": ["Aalo", "Yomcha", "Kamba", "Liromoba"]
  },
  "Assam": {
    "Baksa": ["Mushalpur", "Tamulpur", "Salbari", "Barama"],
    "Barpeta": ["Barpeta", "Howly", "Sarthebari", "Pathsala", "Jania"],
    "Biswanath": ["Biswanath Chariali", "Gohpur", "Helem", "Borgang"],
    "Bongaigaon": ["Bongaigaon", "Abhayapuri", "Bijni", "Manikpur"],
    "Cachar": ["Silchar", "Lakhipur", "Sonai", "Katigorah", "Baskandi"],
    "Charaideo": ["Sonari", "Mahmora", "Sapekhati", "Moran"],
    "Chirang": ["Kajalgaon", "Sidli", "Runikhata", "Bijni"],
    "Darrang": ["Mangaldai", "Sipajhar", "Dalgaon", "Kalaigaon"],
    "Dhemaji": ["Dhemaji", "Jonai", "Silapathar", "Gogamukh"],
    "Dhubri": ["Dhubri",, "Gauripur", "Bilasipara", "Golakganj", "South Salmara"],
    "Dibrugarh": ["Dibrugarh", "Tinsukia Road", "Chabua", "Moran", "Naharkatia"],
    "Dima Hasao": ["Haflong", "Umrangso", "Mahur", "Maibang"],
    "Goalpara": ["Goalpara", "Dudhnoi", "Lakhipur", "J源िया"],
    "Golaghat": ["Golaghat", "Dergaon", "Bokakhat", "Sarupathar"],
    "Hailakandi": ["Hailakandi", "Lala", "Katlicherra", "Algapur"],
    "Hojai": ["Hojai", "Lanka", "Doboka", "Lumding"],
    "Jorhat": ["Jorhat", "Majuli Road", "Titabar", "Teok", "Mariani"],
    "Kamrup": ["Amingaon", "Rangasthan", "Boko", "Chaygaon", "Hajo"],
    "Kamrup Metropolitan": ["Guwahati", "Dispur", "Chandrapur", "Sonapur"],
    "Karbi Anglong": ["Diphu", "Bokajan", "Howraghat", "Phuloni"],
    "Karimganj": ["Karimganj", "Badarpur", "Ramkrishna Nagar", "Patharkandi"],
    "Kokrajhar": ["Kokrajhar", "Gossaigaon", "Dotma", "Fakiragram"],
    "Lakhimpur": ["North Lakhimpur", "Bihpuria", "Narayanpur", "Dhakuakhana"],
    "Majuli": ["Garamur", "Kamalabari", "Jhargaon", "Bhogpur"],
    "Morigaon": ["Morigaon", "Jagiroad", "Bhuragaon", "Laharighat"],
    "Nagaon": ["Nagaon", "Raha", "Kaliabor", "Samaguri", "Dhing"],
    "Nalbari": ["Nalbari", "Tihu", "Barb भाग", "Barkhetri"],
    "Sivasagar": ["Sivasagar", "Nazira", "Amguri", "Demow"],
    "Sonitpur": ["Tezpur", "Dhekiajuli", "Jamugurihat", "Rangapara"],
    "South Salmara-Mankachar": ["Hatsingimari", "Mankachar", "Fakirganj"],
    "Tinsukia": ["Tinsukia", "Margherita", "Doomdooma", "Digboi", "Sadiya"],
    "Udalguri": ["Udalguri", "Mazbat", "Harisinga", "Rowta"],
    "West Karbi Anglong": ["Hamren", "Baithalangso", "Donka"]
  },
  "Bihar": {
    "Araria": ["Araria", "Forbesganj", "Raniganj", "Jokihat", "Sikti"],
    "Arwal": ["Arwal", "Kaler", "Karpi", "Kurtha", "Sonbhadra"],
    "Aurangabad": ["Aurangabad", "Daudnagar", "Nabinagar", "Rafiganj", "Obra"],
    "Banka": ["Banka", "Amarpur", "Bauri", "Katoria", "Kullu"],
    "Begusarai": ["Begusarai", "Barauni", "Teghra", "Bakhri", "Balia"],
    "Bhagalpur": ["Bhagalpur", "Kahalgaon", "Naugachhia", "Sultanganj", "Nathnagar"],
    "Bhojpur": ["Ara", "Jagdispur", "Piro", "Shahpur", "Behea"],
    "Buxar": ["Buxar", "Dumraon", "Simri", "Itarhi", "Brahmpur"],
    "Darbhanga": ["Darbhanga", "Benipur", "Baheri", "Keoti", "Singhwara", "Jale"],
    "East Champaran": ["Motihari", "Raxaul", "Areraj", "Chakia", "Dhaka", "Sugauli"],
    "Gaya": ["Gaya", "Bodhgaya", "Sherghati", "Tekari", "Wazirganj", "Belaganj"],
    "Gopalganj": ["Gopalganj", "Mirganj", "Barauli", "Katiya", "Hathwa"],
    "Jamui": ["Jamui", "Jhajha", "Chakai", "Sikandra", "Gidhaur"],
    "Jehanabad": ["Jehanabad", "Makhdumpur", "Ghoshi", "Kako", "Ratni"],
    "Kaimur": ["Bhabua", "Mohania", "Ramgarh", "Kudra", "Chainpur"],
    "Katihar": ["Katihar", "Barsoi", "Korha", "Manihari", "Kadwa"],
    "Khagaria": ["Khagaria", "Gogri", "Beldaur", "Alauli", "Parbatta"],
    "KishanGanj": ["Kishanganj", "Bahadurganj", "Thakurganj", "Pothia", "Kochadhaman"],
    "Lakhisarai": ["Lakhisarai", "Barahiya", "Surajgarha", "Halsi", "Pipariya"],
    "Madhepura": ["Madhepura", "Udakishunganj", "Murliganj", "Singheshwar", "Alamnagar"],
    "Madhubani": ["Madhubani", "Jhanjharpur", "Benipatti", "Jainagar", "Phulparas"],
    "Munger": ["Munger", "Jamalpur", "Kharagpur", "Tarapur", "Bariarpur"],
    "Muzaffarpur": ["Muzaffarpur", "Kanti", "Motipur", "Kurhani", "Bochahan", "Sakra"],
    "Nalanda": ["Bihar Sharif", "Rajgir", "Hilsa", "Islampur", "Harnaut"],
    "Nawada": ["Nawada", "Rajauli", "Hisua", "Warisaliganj", "Pakribarawan"],
    "Patna": ["Patna", "Danapur", "Phulwari Sharif", "Bihta", "Fatuha", "Bakhtiyarpur", "Masaurhi"],
    "Purnia": ["Purnia", "Banmankhi", "Dhamdaha", "Kasba", "Kirtyanand Nagar", "Baisa"],
    "Rohtas": ["Sasaram", "Dehri", "Bikramganj", "Nokha", "Chenari"],
    "Saharsa": ["Saharsa", "Simri Bakhtiyarpur", "Sonbarsa", "Kahra", "Salkhua"],
    "Samastipur": ["Samastipur", "Dalsinghsarai", "Rosera", "Shahpur Patori", "Tajpur"],
    "Saran": ["Chhapra", "Marhaura", "Sonpur", "Garkha", "Manjhi", "Revelganj"],
    "Sheikhpura": ["Sheikhpura", "Barbigha", "Chewara", "Ariari", "Shekhopur Sarai"],
    "Sheohar": ["Sheohar", "Tariyani", "Piprahi", "Dumri Katsari"],
    "Sitamarhi": ["Sitamarhi", "Pupri", "Bairgania", "Sursand", "Dumra"],
    "Siwan": ["Siwan", "Mairwa", "Maharajganj", "Raghunathpur", "Darauli"],
    "Supaul": ["Supaul", "Triveniganj", "Nirmali", "Birpur", "Bhitthan"],
    "Vaishali": ["Hajipur", "Lalganj", "Mahua", "Jandaha", "Bidupur"],
    "West Champaran": ["Bettiah", "Bagaha", "Narkatiaganj", "Ramnagar", "Lauriya"]
  },
  "Chhattisgarh": {
    "Balod": ["Balod", "Gunderdehi", "Dondilohara", "Gurur", "Dondi"],
    "Baloda Bazar": ["Baloda Bazar", "Bhatapara", "Kasdol", "Simga", "Palari"],
    "Balrampur": ["Balrampur", "Ramanujganj", "Rajpur", "Wadrafnagar", "Samri"],
    "Bastar": ["Jagdalpur", "Bastanar", "Bhanpuri", "Bakawand", "Lohandiguda"],
    "Bemetara": ["Bemetara", "Berla", "Nawagarh", "Saja", "Than Khamhariya"],
    "Bijapur": ["Bijapur", "Bhairamgarh", "Bhopalpatnam", "Usur"],
    "Bilaspur": ["Bilaspur", "Kota", "Takhatpur", "Masturi", "Bilha"],
    "Dantewada": ["Dantewada", "Gidam", "Kuakonda", "Katekalyan"],
    "Dhamtari": ["Dhamtari", "Kurud", "Nagri", "Magarlod"],
    "Durg": ["Durg", "Bhilai", "Patan", "Dhamdha"],
    "Gariaband": ["Gariaband", "Rajim", "Chhura", "Fingeshwar", "Mainpur"],
    "Gaurela-Pendra-Marwahi": ["Pendra", "Gaurela", "Marwahi"],
    "Janjgir-Champa": ["Janjgir", "Champa", "Akaltara", "Pamgarh", "Nawagarh"],
    "Jashpur": ["Jashpur", "Kunkuri", "Pathalgaon", "Bagicha", "DulDula"],
    "Kabirdham": ["Kawardha", "Pandariya", "Bodla", "Sahaspur Lohara"],
    "Kanker": ["Kanker", "Charama", "Narharpur", "Bhanupratappur", "Antagarh"],
    "Kondagaon": ["Kondagaon", "Keshkal", "Farasgaon", "Bade Rajpur", "Makdi"],
    "Korba": ["Korba", "Katghora", "Pali", "Kartala", "Poundi Uprora"],
    "Koriya": ["Baikunthpur", "Sonhat", "Manendragarh", "Khadgawan"],
    "Mahasamund": ["Mahasamund", "Bagbahra", "Pithora", "Saraipali", "Basna"],
    "Manendragarh-Chirmiri-Bharatpur": ["Chirmiri", "Manendragarh", "Bharatpur", "Khonga Pani"],
    "Mohla-Manpur-Ambagarh Chowki": ["Mohla", "Manpur", "Ambagarh Chowki"],
    "Mungeli": ["Mungeli", "Lormi", "Pathariya"],
    "Narayanpur": ["Narayanpur", "Orcha"],
    "Raigarh": ["Raigarh", "Kharsia", "Sarangarh", "Dharamjaigarh", "Gharghoda"],
    "Raipur": ["Raipur", "Abhanpur", "Arang", "Tilda Newra"],
    "Rajnandgaon": ["Rajnandgaon", "Dongargarh", "Dongargaon", "Khairagarh"],
    "Sarangarh-Bilaigarh": ["Sarangarh", "Bilaigarh", "Baramkela"],
    "Sukma": ["Sukma", "Kontan", "Chhintagufa"],
    "Surajpur": ["Surajpur", "Bhaiyathan", "Pratappur", "Ogiya", "Ramanujnagar"],
    "Surguja": ["Ambikapur", "Sitapur", "Lundra", "Mainpat", "Udaipur"]
  },
  "Goa": {
    "North Goa": ["Panaji", "Mapusa", "Ponda", "Bicholim", "Pernem", "Valpoi"],
    "South Goa": ["Margao", "Vasco da Gama", "Quepem", "Sanguem", "Canacona", "Curchorem"]
  },
  "Gujarat": {
    "Ahmedabad": ["Ahmedabad", "Sanand", "Dholka", "Dhandhuka", "Viramgam", "Bavla"],
    "Amreli": ["Amreli", "Dhari", "Rajula", "Savarkundla", "Babra", "Bagsara"],
    "Anand": ["Anand", "Nadiad Road", "Khambhat", "Petlad", "Borsad", "Umreth"],
    "Aravalli": ["Modasa", "Bhiloda", "Bayad", "Dhansura", "Malpur"],
    "Banaskantha": ["Palanpur", "Deesa", "Tharad", "Dantiwada", "Kankrej", "Dhanera"],
    "Bharuch": ["Bharuch", "Ankleshwar", "Jambusar", "Hansot", "Vagra", "Amod"],
    "Bhavnagar": ["Bhavnagar", "Palitana", "Mahuva", "Talaja", "Gadhada", "Sihor"],
    "Botad": ["Botad", "Gadhada", "Barwala", "Ranpur"],
    "Chhota Udepur": ["Chhota Udepur", "Jetpur Pavi", "Bodeli", "Sankheda", "Nasvadi"],
    "Dahod": ["Dahod", "Jhalod", "Limkheda", "Devgadh Baria", "Garbada"],
    "Dang": ["Ahwa", "Waghai", "Subir"],
    "Devbhumi Dwarka": ["Khambhalia", "Dwarka", "Kalyanpur", "Bhanvad"],
    "Gandhinagar": ["Gandhinagar", "Kalol", "Mansa", "Dehgam"],
    "Gir Somnath": ["Veraval", "Somnath", "Talala", "Una", "Kodinar"],
    "Jamnagar": ["Jamnagar", "Jamjodhpur", "Jodiya", "Dhrol", "Lalpur"],
    "Junagadh": ["Junagadh", "Keshod", "Malia", "Manavadar", "Visavadar", "Vanthali"],
    "Kheda": ["Nadiad", "Kheda", "Kapadvanj", "Mahudha", "Matar", "Thasra"],
    "Kutch": ["Bhuj", "Gandhidham", "Anjar", "Mandvi", "Mundra", "Rapar"],
    "Mahisagar": ["Lunawada", "Santrampur", "Balasinor", "Virpur", "Kadana"],
    "Mehsana": ["Mehsana", "Unjha", "Visnagar", "Kadi", "Vadnagar", "Becharaji"],
    "Morbi": ["Morbi", "Wankaner", "Halvad", "Tankara", "Maliya"],
    "Narmada": ["Rajpipla", "Nandod", "Dediapada", "Sagbara", "Tilakwada"],
    "Navsari": ["Navsari", "Gandevi", "Chikhli", "Vansda", "Jalalpore"],
    "Panchmahal": ["Godhra", "Halol", "Kalol", "Shehra", "Ghoghamba"],
    "Patan": ["Patan", "Siddhpur", "Chanasma", "Radhanpur", "Harij", "Sami"],
    "Porbandar": ["Porbandar", "Ranavav", "Kutiyana"],
    "Rajkot": ["Rajkot", "Gondal", "Jetpur", "Jasdan", "Dhoraji", "Upleta"],
    "Sabarkantha": ["Himatnagar", "Idar", "Khedbrahma", "Vadali", "Prantij"],
    "Surat": ["Surat", "Bardoli", "Kamrej", "Olpad", "Mahuva", "Mandvi"],
    "Surendranagar": ["Surendranagar", "Wadhwan", "Dhrangadhra", "Limbdi", "Chotila"],
    "Tapi": ["Vyara", "Songadh", "Valod", "Nizar", "Uchchhal"],
    "Vadodara": ["Vadodara", "Padra", "Dabhoi", "Karjan", "Savli", "Waghodia"],
    "Valsad": ["Valsad", "Vapi", "Pardi", "Umbergaon", "Kaprada", "Dharampur"]
  },
  "Haryana": {
    "Ambala": ["Ambala Cantt", "Ambala City", "Barara", "Naraingarh", "Saha"],
    "Bhiwani": ["Bhiwani", "Charkhi Dadri", "Tosham", "Bawani Khera", "Loharu"],
    "Charkhi Dadri": ["Charkhi Dadri", "Badhra", "Bond Kalan"],
    "Faridabad": ["Faridabad", "Ballabgarh", "Tigaon", "Mohna"],
    "Fatehabad": ["Fatehabad", "Ratia", "Tohana", "Bhuna"],
    "Gurugram": ["Gurugram", "Manesar", "Pataudi", "Farrukhnagar", "Sohna"],
    "Hisar": ["Hisar", "Hansi", "Adampur", "Barwala", "Narnaund", "Uklana"],
    "Jhajjar": ["Jhajjar", "Bahadurgarh", "Beri", "Matanhail"],
    "Jind": ["Jind", "Narwana", "Safidon", "Uchana", "Julana"],
    "Kaithal": ["Kaithal", "Guhla", "Pundri", "Kalayat", "Rajound"],
    "Karnal": ["Karnal", "Gharaunda", "Indri", "Assandh", "Nilokheri", "Taraori", "Kunjpura"],
    "Kurukshetra": ["Thanesar", "Pehowa", "Shahbad", "Ladwa", "Babain"],
    "Mahendragarh": ["Narnaul", "Mahendragarh", "Kanina", "Ateli", "Nangal Choudhary"],
    "Nuh": ["Nuh", "Ferozepur Jhirka", "Punhana", "Taoru"],
    "Palwal": ["Palwal", "Hodal", "Hathin", "Hassanpur"],
    "Panchkula": ["Panchkula", "Kalka", "Pinjore", "Raipur Rani"],
    "Panipat": ["Panipat", "Samalkha", "Israna", "Madlauda", "Bapoli"],
    "Rewari": ["Rewari", "Bawal", "Kosli", "Dharuhera"],
    "Rohtak": ["Rohtak", "Meham", "Sampla", "Kalanaur"],
    "Sirsa": ["Sirsa", "Dabwali", "Rania", "Ellenabad", "Kalanwali"],
    "Sonipat": ["Sonipat", "Gohana", "Ganaur", "KharKhoda", "Rai"],
    "Yamunanagar": ["Yamunanagar", "Jagadhri", "Chhachhrauli", "Radaur", "Sadhaura"]
  },
  "Himachal Pradesh": {
    "Bilaspur": ["Bilaspur", "Ghumarwin", "Jhandutta", "Swarghat"],
    "Chamba": ["Chamba", "Dalhousie", "Chowari", "Bharmour", "Pangi", "Salooni"],
    "Hamirpur": ["Hamirpur", "Nadaun", "Sujanpur", "Barsar", "Bhoranj"],
    "Kangra": ["Dharamshala", "Kangra", "Palampur", "Nurpur", "Dehra Gopipur", "Jawali"],
    "Kinnaur": ["Reckong Peo", "Kalpa", "Nichar", "Pooh"],
    "Kullu": ["Kullu", "Manali", "Banjar", "Anni", "Nirmand"],
    "Lahaul and Spiti": ["Keylong", "Udaipur", "Kaza", "Tabo"],
    "Mandi": ["Mandi", "Sundernagar", "Sarkaghat", "Jogindernagar", "Karsog"],
    "Shimla": ["Shimla", "Rampur", "Theog", "Rohru", "Chopal", "Jubbal"],
    "Sirmaur": ["Nahan", "Paonta Sahib", "Rajgarh", "Shillai", "Dadahu"],
    "Solan": ["Solan", "Baddi", "Nalagarh", "Arki", "Kasauli"],
    "Una": ["Una", "Amb", "Bangana", "Haroli", "Gagret"]
  },
  "Jharkhand": {
    "Bokaro": ["Bokaro Steel City", "Chas", "Bermo", "Phusro", "Gomia", "Chandan Kiyari"],
    "Chatra": ["Chatra", "Simaria", "Hunterganj", "Tandwa", "Itkhori"],
    "Deoghar": ["Deoghar", "Madhupur", "Sarath", "Palojori", "Mohanpur"],
    "Dhanbad": ["Dhanbad", "Jharia", "Katras", "Nirsa", "Govindpur", "Sindri"],
    "Dumka": ["Dumka", "Jarmundi", "Raneshwar", "Masalia", "Jama"],
    "East Singhbhum": ["Jamshedpur", "Ghatshila", "Baharagora", "Potka", "Patamda"],
    "Garhwa": ["Garhwa", "Nagar Untari", "Ranka", "Majhiaon", "Dhurki"],
    "Giridih": ["Giridih", "Dumri", "Bagodar", "Rajdhanwar", "Tisri"],
    "Godda": ["Godda", "Mahagama", "Poreyahat", "Pathargama", "Boarijor"],
    "Gumla": ["Gumla", "Chainpur", "Raidih", "Palkot", "Sisai"],
    "Hazaribagh": ["Hazaribagh", "Barhi", "Chorparan", "Barkagaon", "Ichak"],
    "Jamtara": ["Jamtara", "Nala", "Narayanpur", "Kundu"],
    "Khunti": ["Khunti", "Murhu", "Torpa", "Rania", "Karra"],
    "Koderma": ["Jhumri Telaiya", "Koderma", "Jainagar", "Markacho", "Satgawan"],
    "Latehar": ["Latehar", "Chandwa", "Balumath", "Mahuadanr", "Manika"],
    "Lohardaga": ["Lohardaga", "Kuru", "Bhandra", "Kisko", "Senha"],
    "Pakur": ["Pakur", "Littipara", "Amrapara", "Hiranpur", "Maheshpur"],
    "Palamu": ["Daltonganj", "Medininagar", "Chhatarpur", "Hussainabad", "Lesliganj"],
    "Ramgarh": ["Ramgarh Cantonment", "Patratu", "Gola", "Mandu"],
    "Ranchi": ["Ranchi", "Kanke", "Namkum", "Ormanjhi", "Bundu", "Silli", "Itki"],
    "Sahibganj": ["Sahibganj", "Rajmahal", "Bharharwa", "Borio", "Taljhari"],
    "Seraikela Kharsawan": ["Seraikela", "Adityapur", "Chandil", "Kharsawan", "Gamharia"],
    "Simdega": ["Simdega", "Kolebira", "Bano", "Kurdeg", "Thethaitangar"],
    "West Singhbhum": ["Chaibasa", "Chakradharpur", "Noamundi", "Jagannathpur", "Jhinkpani"]
  },
  "Karnataka": {
    "Bagalkot": ["Bagalkot", "Badami", "Hungund", "Ilkal", "Jamkhandi", "Mudhol"],
    "Ballari": ["Ballari", "Kampli", "Siruguppa", "Sandur", "Kurugodu"],
    "Belagavi": ["Belagavi", "Gokak", "Chikkodi", "Bailhongal", "Athani", "Ramdurg"],
    "Bengaluru Rural": ["Nelamangala", "Doddaballapura", "Devanahalli", "Hoskote"],
    "Bengaluru Urban": ["Bengaluru", "Yelahanka", "Kengeri", "Electronic City", "Anekal"],
    "Bidar": ["Bidar", "Basavakalyan", "Bhalki", "Humnabad", "Aurad"],
    "Chamarajanagar": ["Chamarajanagar", "Gundlupet", "Kollegal", "Yelandur"],
    "Chikkaballapura": ["Chikkaballapura", "Gauribidanur", "Sidlaghatta", "Chintamani", "Bagepalli"],
    "Chikkamagaluru": ["Chikkamagaluru", "Kadur", "Tarikere", "Mudigere", "Sringeri"],
    "Chitradurga": ["Chitradurga", "Challakere", "Hiriyur", "Hosadurga", "Holalkere"],
    "Dakshina Kannada": ["Mangaluru", "Bantwal", "Puttur", "Belthangady", "Sullia"],
    "Davanagere": ["Davanagere", "Harihar", "Honnali", "Channagiri", "Jagalur"],
    "Dharwad": ["Dharwad", "Hubballi", "Kalghatgi", "Kundgol", "Navalgund"],
    "Gadag": ["Gadag", "Ron", "Shirhatti", "Nargund", "Mundargi"],
    "Hassan": ["Hassan", "Arsikere", "Channarayapatna", "Holenarasipura", "Sakleshpur"],
    "Haveri": ["Haveri", "Ranebennur", "Byadgi", "Hirekerur", "Shiggaon"],
    "Kalaburagi": ["Kalaburagi", "Sedam", "Chincholi", "Aland", "Jevargi"],
    "Kodagu": ["Madikeri", "Somwarpet", "Virajpet", "Kushaalnagar"],
    "Kolar": ["Kolar", "Bangarapet", "Malur", "Mulbagal", "Srinivaspur"],
    "Koppal": ["Koppal", "Gangavathi", "Yelbarga", "Kushtagi"],
    "Mandya": ["Mandya", "Maddur", "Srirangapatna", "Malavalli", "Pandavapura"],
    "Mysuru": ["Mysuru", "Nanjangud", "Hunsur", "T. Narasipura", "KR Nagar"],
    "Raichur": ["Raichur", "Manvi", "Sindhanur", "Devadurga", "Lingsugur"],
    "Ramanagara": ["Ramanagara", "Channapatna", "Kanakapura", "Magadi"],
    "Shivamogga": ["Shivamogga", "Bhadravathi", "Sagara", "Shikaripura", "Thirthahalli"],
    "Tumakuru": ["Tumakuru", "Tiptur", "Sira", "Gubbi", "Kunigal", "Madhugiri"],
    "Udupi": ["Udupi", "Kundapura", "Karkala", "Kapu", "Brahmavar"],
    "Uttara Kannada": ["Karwar", "Sirsi", "Bhatkal", "Dandeli", "Kumta", "Honnavar"],
    "Vijayanagara": ["Hosapete", "Hampi", "Harapanahalli", "Kudligi", "Hoovina Hadagali"],
    "Yadgir": ["Yadgir", "Shahapur", "Shorapur", "Gurmatkal"]
  },
  "Kerala": {
    "Alappuzha": ["Alappuzha", "Cherthala", "Kayamkulam", "Mavelikkara", "Chengannur", "Ambalappuzha"],
    "Ernakulam": ["Kochi", "Aluva", "Angamaly", "Perumbavoor", "Muvattupuzha", "Kothamangalam"],
    "Idukki": ["Thodupuzha", "Munnar", "Kattappana", "Adimali", "Nedumkandam"],
    "Kannur": ["Kannur", "Thalassery", "Payyanur", "Mattannur", "Taliparamba"],
    "Kasaragod": ["Kasaragod", "Kanhangad", "Nileshwaram", "Uppala", "Cheruvathur"],
    "Kollam": ["Kollam", "Karunagappally", "Punalur", "Kottarakkara", "Paravur"],
    "Kottayam": ["Kottayam", "Changanassery", "Pala", "Kanjirappally", "Vaikom"],
    "Kozhikode": ["Kozhikode", "Vatakara", "Koyilandy", "Thamarassery", "Ramanattukara"],
    "Malappuram": ["Malappuram", "Manjeri", "Perinthalmanna", "Tirur", "Ponnani", "Nilambur"],
    "Palakkad": ["Palakkad", "Ottapalam", "Chittur", "Mannarkkad", "Pattambi", "Shornur"],
    "Pathanamthitta": ["Pathanamthitta", "Tiruvalla", "Adoor", "Ranni", "Pandalam"],
    "Thiruvananthapuram": ["Thiruvananthapuram", "Neyyattinkara", "Attingal", "Varkala", "Nedumangad"],
    "Thrissur": ["Thrissur", "Chalakudy", "Guruvayur", "Irinjalakuda", "Kodungallur", "Kunnamkulam"],
    "Wayanad": ["Kalpetta", "Mananthavady", "Sulthan Bathery", "Meppadi"]
  },
  "Madhya Pradesh": {
    "Agar Malwa": ["Agar", "Nalkheda", "Susner", "Badod"],
    "Alirajpur": ["Alirajpur", "Jobat", "Bhabra", "Katthiwada"],
    "Anuppur": ["Anuppur", "Kotma", "Jaithari", "Rajendragram"],
    "Ashoknagar": ["Ashoknagar", "Chanderi", "Mungawali", "Isagarh"],
    "Balaghat": ["Balaghat", "Waraseoni", "Katangi", "Baihar", "Lanji"],
    "Barwani": ["Barwani", "Sendhwa", "Anjad", "Rajpur", "Khetia"],
    "Betul": ["Betul", "Multai", "Amla", "Shahpur", "Bhainsdehi"],
    "Bhind": ["Bhind", "Mehgaon", "Gohad", "Lahar", "Ater"],
    "Bhopal": ["Bhopal", "Berasia", "Huzur", "Phanda", "Kolar"],
    "Burhanpur": ["Burhanpur", "Nepanagar", "Khaknar"],
    "Chhatarpur": ["Chhatarpur", "Nowgong", "Khajuraho", "Buxwaha", "Laundi"],
    "Chhindwara": ["Chhindwara", "Sausar", "Pandhurna", "Parasia", "Junardeo", "Amarwara"],
    "Damoh": ["Damoh", "Hatta", "Patharia", "Jabera", "Tendukheda"],
    "Datia": ["Datia", "Seondha", "Bhander", "Indergarh"],
    "Dewas": ["Dewas", "Sonkatch", "Hatpiplya", "Bagli", "Tonk Khurd", "Kannod"],
    "Dhar": ["Dhar", "Pithampur", "Badnawar", "Sardarpur", "Kukshi", "Manawar"],
    "Dindori": ["Dindori", "Shahpura", "Mehendwani", "Amarpur"],
    "Guna": ["Guna", "Raghogarh", "Aaron", "Kumbhraj", "Chachoda"],
    "Gwalior": ["Gwalior", "Dabra", "Bhantar", "Morar", "Chinor"],
    "Harda": ["Harda", "Timarni", "Khirkiya"],
    "Hoshangabad (Narmadapuram)": ["Itarsi", "Hoshangabad", "Pipariya", "Seoni Malwa", "Sohagpur"],
    "Indore": ["Indore", "Mhow", "Sanwer", "Depalpur", "Rau", "Hatod"],
    "Jabalpur": ["Jabalpur", "Patan", "Sihora", "Kundam", "Panagar", "Shahpura"],
    "Jhabua": ["Jhabua", "Thandla", "Petlawad", "Ranapur", "Meghnagar"],
    "Katni": ["Katni", "Murwara", "Vijayraghavgarh", "Bahoriband", "Sleemanabad"],
    "Khandwa (East Nimar)": ["Khandwa", "Pandhana", "Harsud", "Punasa", "Mundi"],
    "Khargone (West Nimar)": ["Khargone", "Sanawad", "Kasrawad", "Maheshwar", "Barwaha"],
    "Mandla": ["Mandla", "Nainpur", "Bichhiya", "Niwas"],
    "Mandsaur": ["Mandsaur", "Neemuch Road", "Sitamau", "Bhanpura", "Garoth", "Malhargarh"],
    "Morena": ["Morena", "Ambah", "Joura", "Sabalgarh", "Porsa"],
    "Narsinghpur": ["Narsinghpur", "Gadarwara", "Kareli", "Gotegaon"],
    "Neemuch": ["Neemuch", "Manasa", "Jawad", "Singoli"],
    "Niwari": ["Niwari", "Orchha", "Prithvipur"],
    "Panna": ["Panna", "Pawai", "Gunour", "Ajaigarh", "Shahnagar"],
    "Raisen": ["Raisen", "Mandi Bamora", "GoharGanj", "Begumganj", "Barei"],
    "Rajgarh": ["Rajgarh", "Biaora", "Narsinghgarh", "Sarangpur", "Zirapur"],
    "Ratlam": ["Ratlam", "Jaora", "Sailana", "Alot", "Piploda"],
    "Rewa": ["Rewa", "Mauganj", "Teonthar", "Hanumana", "Semaria", "Mangawan"],
    "Sagar": ["Sagar", "Bina", "Khurai", "Rehli", "Deori", "Banda"],
    "Satna": ["Satna", "Maihar", "Nagod", "Amarpatan", "Chitrakoot", "Rampur Baghelan"],
    "Sehore": ["Sehore", "Ashta", "Ichhawar", "Budhni", "Nasrullaganj"],
    "Seoni": ["Seoni", "Lakhnadon", "Ghansore", "Barghat", "Chhapara"],
    "Shahdol": ["Shahdol", "Burhar", "Beohari", "Jaisinghnagar"],
    "Shajapur": ["Shajapur", "Shujalpur", "Kalapipal", "Akodia"],
    "Sheopur": ["Sheopur", "Vijaypur", "Karatwad"],
    "Shivpuri": ["Shivpuri", "Karera", "Pohri", "Kolaras", "Khaniadhana"],
    "Sidhi": ["Sidhi", "Gopadbanas", "Churhat", "Rampur Naikin", "Majhauli"],
    "Singrauli": ["Singrauli", "Waidhan", "Chitrangi", "Deosar"],
    "Takamgarh": ["Tikamgarh", "Jatara", "Palera", "Baldeogarh"],
    "Ujjain": ["Ujjain", "Nagda", "Khachrod", "Mahidpur", "Tarana", "Barnagar"],
    "Umaria": ["Umaria", "Pali", "Manpur", "Chandia"],
    "Vidisha": ["Vidisha", "Basoda", "Sironj", "Kurwai", "Lateri"]
  },
  "Maharashtra": {
    "Ahmednagar (Ahilyanagar)": ["Ahmednagar", "Shirdi", "Sangamner", "Kopargaon", "Shrirampur", "Rahuri"],
    "Akola": ["Akola", "Akot", "Murtizapur", "Telhara", "Balapur"],
    "Amravati": ["Amravati", "Achalpur", "Warud", "Morshi", "Daryapur", "Anjangaon"],
    "Chhatrapati Sambhajinagar (Aurangabad)": ["Chhatrapati Sambhajinagar", "Gangapur", "Paithan", "Vaijapur", "Kannad", "Sillod"],
    "Beed": ["Beed", "Parli", "Ambejogai", "Georai", "Majalgaon"],
    "Bhandara": ["Bhandara", "Tumsar", "Sakoli", "Pauni", "Mohadi"],
    "Buldhana": ["Buldhana", "Khamgaon", "Malkapur", "Shegaon", "Chikhli", "Mehkar"],
    "Chandrapur": ["Chandrapur", "Ballarpur", "Warora", "Bhadravati", "Rajura"],
    "Dhule": ["Dhule", "Shirpur", "Sakri", "Sindkheda"],
    "Gadchiroli": ["Gadchiroli", "Aheri", "Armori", "Chamorshi", "Kurkheda"],
    "Gondia": ["Gondia", "Tiroda", "Arjuni Morgaon", "Deori", "Amgaon"],
    "Hingoli": ["Hingoli", "Basmath", "Kalamnuri", "Sengaon", "Aundha Nagnath"],
    "Jalgaon": ["Jalgaon", "Bhusawal", "Chalisgaon", "Amalner", "Pachora", "Yawal"],
    "Jalna": ["Jalna", "Ambad", "Partur", "Bhokardan", "Jafrabad"],
    "Kolhapur": ["Kolhapur", "Ichalkaranji", "Kagal", "Karveer", "Shirol", "Gadhinglaj"],
    "Latur": ["Latur", "Udgir", "Ahmedpur", "Nilanga", "Ausa"],
    "Mumbai City": ["Fort", "Colaba", "Dadabhai Naoroji Road", "Marine Lines", "Girgaon", "Byculla"],
    "Mumbai Suburban": ["Andheri", "Bandra", "Borivali", "Kurla", "Ghatkopar", "Malad"],
    "Nagpur": ["Nagpur", "Kamptee", "Ramtek", "Katol", "Umred", "Saoner", "Hingna"],
    "Nanded": ["Nanded", "Degloor", "Kinwat", "Hadgaon", "Mukhed", "Loha"],
    "Nandurbar": ["Nandurbar", "Shahada", "Navapur", "Taloda", "Akkalkuwa"],
    "Nashik": ["Nashik", "Malegaon", "Sinnar", "Niphad", "Yeola", "Igatpuri"],
    "Dharashiv (Osmanabad)": ["Dharashiv", "Tuljapur", "Omerga", "Kalamb", "Bhum"],
    "Palghar": ["Palghar", "Vasai-Virar", "Dahanu", "Wada", "Jawhar", "Boisar"],
    "Parbhani": ["Parbhani", "Gangakhed", "Pathri", "Jintur", "Sailu"],
    "Pune": ["Pune", "Baramati", "Haveli", "Shirur", "Junnar", "Indapur", "Daund", "Pimpri-Chinchwad"],
    "Raigad": ["Alibag", "Panvel", "Karjat", "Mahad", "Pen", "Roha", "Khadakwasla"],
    "Ratnagiri": ["Ratnagiri", "Chiplun", "Khed", "Rajapur", "Guhagar", "Dapoli"],
    "Sangli": ["Sangli", "Miraj", "Vita", "Islampur", "Jath", "Tasgaon"],
    "Satara": ["Satara", "Karad", "Wai", "Phaltan", "Mahabaleshwar", "Koregaon"],
    "Sindhudurg": ["Oros", "Kankavli", "Malvan", "Sawantwadi", "Vengurla", "Kudal"],
    "Solapur": ["Solapur", "Pandharpur", "Barshi", "Akkalkot", "Sangola", "Mohol"],
    "Thane": ["Thane", "Bhiwandi", "Kalyan-Dombivli", "Ulhasnagar", "Shahapur", "Murbad"],
    "Wardha": ["Wardha", "Hinganghat", "Arvi", "Deoli", "Pulgaon"],
    "Washim": ["Washim", "Karanja Lad", "Risod", "Mangrulpir", "Manora"],
    "Yavatmal": ["Yavatmal", "Pusad", "Umarkhed", "Wani", "Digras", "Darwha"]
  },
  "Manipur": {
    "Bishnupur": ["Bishnupur", "Moirang", "Nambol", "Kumbhi"],
    "Chandel": ["Chandel", "Maki", "Chakpikarong"],
    "Churachandpur": ["Churachandpur", "Tuibong", "Singngat", "Thanlon"],
    "Imphal East": ["Porompat", "Lamlai", "Keirao", "Sawombung"],
    "Imphal West": ["Lamphelpat", "Patsoi", "Lamsang", "Wangoi"],
    "Jiribam": ["Jiribam", "Borobekra"],
    "Kakching": ["Kakching", "Wabagai", "Sugnoo"],
    "Kamjong": ["Kamjong", "Phungyar", "Kasom Khullen"],
    "Kangpokpi": ["Kangpokpi", "Saikul", "Saitu Gamphazol"],
    "Noney": ["Noney", "Longmai", "Nungba", "Khoupum"],
    "Pherzawl": ["Pherzawl", "Parbung", "Vangai"],
    "Senapati": ["Senapati", "Maram", "Paomata", "Purul"],
    "Tamenglong": ["Tamenglong", "Tamei", "Tousem"],
    "Tengnoupal": ["Tengnoupal", "Moreh", "Machhi"],
    "Thoubal": ["Thoubal", "Lilong", "Yairipok", "Heirok"],
    "Ukhrul": ["Ukhrul", "Litan", "Chingai", "Kamjong Road"]
  },
  "Meghalaya": {
    "East Garo Hills": ["Williamnagar", "Rongjeng", "Samanda"],
    "East Jaintia Hills": ["Khliehriat", "Saipung", "Sutnga"],
    "East Khasi Hills": ["Shillong", "Sohra (Cherrapunji)", "Pynursla", "Mawsynram", "Mawkynrew"],
    "Eastern West Khasi Hills": ["Mairang", "Mawthadraishan"],
    "North Garo Hills": ["Resubelpara", "Kharkutta", "Mendipathar"],
    "Ri Bhoi": ["Nongpoh", "Umsning", "Bhoirymbong", "Byrnihat"],
    "South Garo Hills": ["Baghmara", "Chokpot", "Rongara"],
    "South West Garo Hills": ["Ampati", "Zikzak", "Betasing"],
    "South West Khasi Hills": ["Mawkyrwat", "Ranikor"],
    "West Garo Hills": ["Tura", "Phulbari", "Dadenggre", "Tikrikilla", "Rongram"],
    "West Jaintia Hills": ["Jowai", "Thadlaskein", "Laskein", "Amlarem"],
    "West Khasi Hills": ["Nongstoin", "Mawshynrut"]
  },
  "Mizoram": {
    "Aizawl": ["Aizawl", "Darlawn", "Phullen", "Thingsulthliah"],
    "Champhai": ["Champhai", "Khawbung", "Ngopa"],
    "Hnahthial": ["Hnahthial", "South Vanlaiphai"],
    "Khawzawl": ["Khawzawl", "Rabung"],
    "Kolasib": ["Kolasib", "Vairengte", "Bairabi", "Kawnpui"],
    "Lawngtlai": ["Lawngtlai", "Sangau", "Chawngte", "Bungtlang South"],
    "Lunglei": ["Lunglei", "Tlabung", "Hraangchalkawn", "Bunghmun"],
    "Mamit": ["Mamit", "Zawlnuam", "West Phaileng"],
    "Saitual": ["Saitual", "Suangpuilawn"],
    "Serchhip": ["Serchhip", "Thenzawl", "East Lungdar"],
    "Siaha": ["Siaha", "Tipa", "Phura"]
  },
  "Nagaland": {
    "Chümoukedima": ["Chümoukedima", "Medziphema", "Seithekema"],
    "Dimapur": ["Dimapur", "Dhansiri", "Kuhuboto"],
    "Kiphire": ["Kiphire", "Pungro", "Seyochung"],
    "Kohima": ["Kohima", "Chiephobozou", "Tseminyu Road", "Sechu-Zubza"],
    "Longleng": ["Longleng", "Tamlu", "Phomching"],
    "Mokokchung": ["Mokokchung", "Tuli", "Changtongya", "Mangkolemba"],
    "Mon": ["Mon", "Tizit", "Naginimora", "Aboi"],
    "Niuland": ["Niuland", "Aghunaqa"],
    "Noklak": ["Noklak", "Thonoknyu"],
    "Peren": ["Peren", "Jalukie", "Tening"],
    "Phek": ["Phek", "Pfutsero", "Meluri", "Chozuba"],
    "Shamator": ["Shamator", "Chessore"],
    "Tseminyu": ["Tseminyu", "Tseminyu South"],
    "Tuensang": ["Tuensang", "Longkhim", "Noksen"],
    "Wokha": ["Wokha", "Bhandari", "Sanis"],
    "Zunheboto": ["Zunheboto", "Satakha", "Pughoboto", "Atoizu"]
  },
  "Odisha": {
    "Angul": ["Angul", "Talcher", "Pallahara", "Athmallik", "Chhendipada"],
    "Balangir": ["Balangir", "Titilagarh", "Patnagarh", "Kantabanji", "Tushura"],
    "Balasore (Baleswar)": ["Balasore", "Bhadrak Road", "Jaleswar", "Soro", "Nilagiri", "Basta"],
    "Bargarh": ["Bargarh", "Padampur", "Attabira", "Sohela", "Barpali"],
    "Bhadrak": ["Bhadrak", "Dhamra", "Basudevpur", "Chandbali", "Banth"],
    "Boudh": ["Boudh", "Kantamal", "Harbhanga"],
    "Cuttack": ["Cuttack", "Choudwar", "Banki", "Athagarh", "Salepur", "Badamba"],
    "Deogarh": ["Deogarh", "Barkote", "Reamal"],
    "Dhenkanal": ["Dhenkanal", "Kamakhyanagar", "Bhuban", "Hindol", "Olapur"],
    "Gajapati": ["Paralakhemundi", "Kashinagara", "Mohana", "R.Udayagiri"],
    "Ganjam": ["Berhampur", "Chatrapur", "Bhanjanagar", "Hinjilicut", "Aska", "Gora"],
    "Jagatsinghpur": ["Jagatsinghpur", "Paradeep", "Tirtol", "Balikuda", "Erasama"],
    "Jajpur": ["Jajpur Town", "Jajpur Road (Vyasanagar)", "Binjharpur", "Sukinda", "Bari"],
    "Jharsuguda": ["Jharsuguda", "Brarajnagar", "Belpahar", "Laikera"],
    "Kalahandi": ["Bhawanipatna", "Kesinga", "Junagarh", "Dharmagarh", "Jaipatna"],
    "Kandhamal": ["Phulbani", "Balliguda", "G.Udayagiri", "Daringbadi", "Kalinga"],
    "Kendrapara": ["Kendrapara", "Pattamundai", "Rajnagar", "Aul", "Derabish"],
    "Kendujhar (Keonjhar)": ["Keonjhar", "Barbil", "Joda", "Anandapur", "Champua"],
    "Khordha": ["Bhubaneswar", "Khordha", "Jatni", "Banapur", "Tangi", "Begunia"],
    "Koraput": ["Koraput", "Jeypore", "Sunabeda", "Kotpad", "Semiliguda"],
    "Malkangiri": ["Malkangiri", "Balimela", "Kalimela", "Mathili", "Chitrakonda"],
    "Mayurbhanj": ["Baripada", "Rairangpur", "Karanjia", "Udala", "Joshipur"],
    "Nabarangpur": ["Nabarangpur", "Umerkote", "Dabugam", "Khatiguda"],
    "Nayagarh": ["Nayagarh", "Ranpur", "Khandapada", "Odagaon", "Daspalla"],
    "Nuapada": ["Nuapada", "Khariar", "Khariar Road", "Sinapali"],
    "Puri": ["Puri", "Konark", "Pipili", "Nimapada", "Delanga", "Brahmagiri"],
    "Rayagada": ["Rayagada", "Gunupur", "Muniguda", "Bissam Cuttack"],
    "Sambalpur": ["Sambalpur", "Burla", "Hirakud", "Rairakhol", "Kuchinda"],
    "Subarnapur (Sonepur)": ["Sonepur", "Birmaharajpur", "Tarbha", "Ullunda"],
    "Sundargarh": ["Rourkela", "Sundargarh", "Rajgangpur", "Bonai", "Biramitrapur"]
  },
  "Punjab": {
    "Amritsar": ["Amritsar", "Ajnala", "Baba Bakala", "Majitha", "Attari", "Jandiala Guru"],
    "Barnala": ["Barnala", "Tapa", "Bhadaur", "Mehal Kalan"],
    "Bathinda": ["Bathinda", "Rampura Phul", "Talwandi Sabo", "Maur", "Bhucho Mandi"],
    "Faridkot": ["Faridkot", "Kotkapura", "Jaitu"],
    "Fatehgarh Sahib": ["Sirhind", "Fatehgarh Sahib", "Mandi Gobindgarh", "Khamanon", "Bassi Pathana"],
    "Fazilka": ["Fazilka", "Abohar", "Jalalabad"],
    "Firozpur": ["Firozpur", "Zira", "Guru Har Sahai", "Makhu"],
    "Gurdaspur": ["Gurdaspur", "Batala", "Dera Baba Nanak", "Dhariwal", "Qadian"],
    "Hoshiarpur": ["Hoshiarpur", "Dasuya", "Mukerian", "Garhshankar", "Tanda"],
    "Jalandhar": ["Jalandhar", "Nakodar", "Phillaur", "Shahkot", "Adampur", "Kartarpur"],
    "Kapurthala": ["Kapurthala", "Phagwara", "Sultanpur Lodhi", "Bholath"],
    "Ludhiana": ["Ludhiana", "Jagraon", "Khanna", "Samrala", "Raikot", "Payal", "Machhiwara"],
    "Malerkotla": ["Malerkotla", "Ahmedgarh", "Amargarh"],
    "Mansa": ["Mansa", "Budhlada", "Sardulgarh"],
    "Moga": ["Moga", "Baghapurana", "Nihal Singh Wala", "Dharamkot"],
    "Pathankot": ["Pathankot", "Sujanpur", "Dhar Kalan"],
    "Patiala": ["Patiala", "Rajpura", "Nabha", "Samana", "Patran", "Ghanaur"],
    "Rupnagar (Ropar)": ["Rupnagar", "Anandpur Sahib", "Nangal", "Morinda", "Chamkaur Sahib"],
    "Sahibzada Ajit Singh Nagar (Mohali)": ["Mohali", "Kharar", "Dera Bassi", "Zirakpur", "Kurali"],
    "Sangrur": ["Sangrur", "Sunam", "Dhuri", "Lehra", "Dirba", "Moonak"],
    "Shahid Bhagat Singh Nagar (Nawanshahr)": ["Nawanshahr", "Banga", "Balachaur"],
    "Sri Muktsar Sahib": ["Muktsar", "Malout", "Gidderbaha"],
    "Tarn Taran": ["Tarn Taran Sahib", "Patti", "Khadur Sahib", "Bhikhiwind"]
  },
  "Rajasthan": {
    "Ajmer": ["Ajmer", "Beawar", "Kishangarh", "Kekri", "Nasirabad", "Pushkar"],
    "Alwar": ["Alwar", "Bhiwadi", "Tijara", "Behror", "Kishangarh Bas", "Rajgarh"],
    "Anupgarh": ["Anupgarh", "Gharshana", "Rawla", "Raisinghnagar"],
    "Balotra": ["Balotra", "Siwana", "Samdari", "Baytu"],
    "Banswara": ["Banswara", "Ghatol", "Garhi", "Kushalgarh", "Bagidora"],
    "Baran": ["Baran", "Chhabra", "Atru", "Antah", "KishanGanj"],
    "Barmer": ["Barmer", "Balotra Road", "Chohtan", "Gudamalani", "Shiv"],
    "Beawar": ["Beawar", "Jaitaran", "Todgarh", "Masuda"],
    "Bharatpur": ["Bharatpur", "Deeg", "Bayana", "Kaman", "Nagar", "Weer"],
    "Bhilwara": ["Bhilwara", "Shahpura", "Mandal", "Asind", "Gulabpura", "Jahazpur"],
    "Bikaner": ["Bikaner", "Nokha", "Kolayat", "Lunkaransar", "Khajuwala", "Dungargarh"],
    "Bundi": ["Bundi", "Keshoraipatan", "Indergarh", "Nainwa", "Hindoli"],
    "Chittorgarh": ["Chittorgarh", "Rawatbhata", "Nimbahera", "Bari Sadri", "Begun", "Kapasan"],
    "Churu": ["Churu", "Ratangarh", "Sujangarh", "Sardarshahar", "Rajgarh", "Taranagar"],
    "Dausa": ["Dausa", "Bandikui", "Lalsot", "Mahwa", "Sikrai"],
    "Deeg": ["Deeg", "Kaman", "Nagar", "Pahari"],
    "Didwana-Kuchaman": ["Didwana", "Kuchaman City", "Makrana", "Nawa", "Parbatsar"],
    "Dholpur": ["Dholpur", "Bari", "Rajakhera", "Baseri"],
    "Dungarpur": ["Dungarpur", "Sagwara", "Aspur", "Bichhiwara", "Simalwara"],
    "Gangapur City": ["Gangapur City", "Bamanwas", "Wazirpur"],
    "Hanumangarh": ["Hanumangarh", "Nohar", "Bhadra", "Pilibanga", "Sangaria", "Rawatsar"],
    "Jaipur": ["Jaipur", "Sanganer", "Amer", "Chaksu", "Kotputli", "Shahpura", "Phulera"],
    "Jaipur Rural": ["Jamwa Ramgarh", "Chomu", "Govindgarh", "Jhotwara"],
    "Jaisalmer": ["Jaisalmer", "Pokhran", "Fatehgarh", "Ramgarh"],
    "Jalore": ["Jalore", "Bhinmal", "Sanchore", "Ahore", "Sayla"],
    "Jhalawar": ["Jhalawar", "Jhalrapatan", "Bhawani Mandi", "Khanpur", "Aklera", "Manohar Thana"],
    "Jhunjhunu": ["Jhunjhunu", "Nawalgarh", "Chirawa", "Khetri", "Pilani", "Bhudhana"],
    "Jodhpur": ["Jodhpur", "Luni", "Bilara", "Osian", "Phalodi", "Shergarh"],
    "Jodhpur Rural": ["Bhopalgarh", "Mandore", "Balesar", "Tinwari"],
    "Karauli": ["Karauli", "Hindaun City", "Todabhim", "Sapotra", "Mandrayal"],
    "Kekri": ["Kekri", "Sarwar", "Bhinai", "Toda Rai Singh"],
    "Khairthal-Tijara": ["Khairthal", "Tijara", "Kishangarh Bas", "Kotkasim"],
    "Kota": ["Kota", "Ladpura", "Sangod", "Ramganj Mandi", "Digod"],
    "Kotputli-Behror": ["Kotputli", "Behror", "Bansur", "Neemrana"],
    "Nagaur": ["Nagaur", "Merta City", "Degana", "Jayal", "Khinvsar"],
    "Neem Ka Thana": ["Neem Ka Thana", "Khandela", "Patan", "Srimadhopur"],
    "Pali": ["Pali", "Sumerpur", "Sojat", "Falna", "Rohat", "Bali"],
    "Phalodi": ["Phalodi", "Lohawat", "Au", "Bap"],
    "Pratapgarh": ["Pratapgarh", "Chhoti Sadri", "Dhariyawad", "Arnod", "Peepalkhoote"],
    "Rajsamand": ["Rajsamand", "Nathdwara", "Kumbhalgarh", "Amet", "Bhim", "Deogarh"],
    "Salumbar": ["Salumbar", "Sarada", "Semari"],
    "Sanchore": ["Sanchore", "Bagoda", "Chitalwana"],
    "Sawai Madhopur": ["Sawai Madhopur", "Gangapur", "Bonli", "Chauth Ka Barwara", "Bamanwas"],
    "Shahpura (Bhilwara)": ["Shahpura", "Jahazpur", "Kotri"],
    "Sikar": ["Sikar", "Fatehpur", "Lachhmangarh", "Dantaramgarh", "Ringas"],
    "Sirohi": ["Sirohi", "Mount Abu", "Abu Road", "Sheoganj", "Reodar"],
    "Sri Ganganagar": ["Sri Ganganagar", "Suratgarh", "Raisinghnagar", "Jaitsar", "Sadulshahar", "Padampur"],
    "Tonk": ["Tonk", "Niwai", "Deoli", "Malpura", "Uniara"],
    "Udaipur": ["Udaipur", "Mavli", "Vallabhnagar", "Salumber", "Jhadol", "Gogunda"]
  },
  "Sikkim": {
    "Gangtok (East Sikkim)": ["Gangtok", "Singtam", "Rangpo", "Pakyong", "Rhenock"],
    "Gyalshing (West Sikkim)": ["Gyalshing", "Pelling", "Dentam", "Naya Bazar"],
    "Mangan (North Sikkim)": ["Mangan", "Chungthang", "Lachen", "Lachung"],
    "Nanchi (South Sikkim)": ["Namchi", "Jorethang", "Ravangla", "Melli"],
    "Pakyong": ["Pakyong", "Rongli", "Rhenock"],
    "Soreng": ["Soreng", "Dharamdin"]
  },
  "Tamil Nadu": {
    "Ariyalur": ["Ariyalur", "Udayarpalayam", "Sendurai", "Andimadam"],
    "Chengalpattu": ["Chengalpattu", "Tambaram", "Pallavaram", "Maduranthakam", "Chengalpet", "Tiruporur"],
    "Chennai": ["T. Nagar", "Adyar", "Anna Nagar", "Mylapore", "Velachery", "Guindy", "Royapettah"],
    "Coimbatore": ["Coimbatore", "Pollachi", "Mettupalayam", "Sulur", "Valparai", "Annur"],
    "Cuddalore": ["Cuddalore", "Chidambaram", "Panruti", "Vriddhachalam", "Neyveli", "Tittakudi"],
    "Dharmapuri": ["Dharmapuri", "Harur", "Palacode", "Pennagaram", "Pappireddipatti"],
    "Dindigul": ["Dindigul", "Palani", "Kodaikanal", "Oddanchatram", "Nattam", "Batlagundu"],
    "Erode": ["Erode", "Gobichettipalayam", "Sathyamangalam", "Bhavani", "Perundurai"],
    "Kallakurichi": ["Kallakurichi", "Tirukkoyilur", "Sankarapuram", "Ulundurpet"],
    "Kanchipuram": ["Kanchipuram", "Sriperumbudur", "Uthiramerur", "Walajabad"],
    "Kanyakumari": ["Nagercoil", "Padmanabhapuram", "Thuckalay", "Kuzhithurai", "Colachel"],
    "Karur": ["Karur", "Kulithalai", "Aravakurichi", "Krishnarayapuram"],
    "Krishnagiri": ["Krishnagiri", "Hosur", "Denkanikottai", "Pochampalli", "Uthangarai"],
    "Madurai": ["Madurai", "Melur", "Tirumangalam", "Usilampatti", "Vadipatti"],
    "Mayiladuthurai": ["Mayiladuthurai", "Sirkali", "Tharangambadi", "Kuthalam"],
    "Nagapattinam": ["Nagapattinam", "Velankanni", "Vedaranyam", "Kilvelur"],
    "Namakkal": ["Namakkal", "Rasipuram", "Tiruchengodu", "Paramathi Velur"],
    "Nilgiris": ["Udhagamandalam (Ooty)", "Coonoor", "Kotagiri", "Gudalur"],
    "Perambalur": ["Perambalur", "Kunnam", "Veppanthattai"],
    "Pudukkottai": ["Pudukkottai", "Aranthangi", "Alangudi", "Iluppur", "Thirumayam"],
    "Ramanathapuram": ["Ramanathapuram", "Rameswaram", "Paramakudi", "Mudukulathur", "Kadaladi"],
    "Ranipet": ["Ranipet", "Arcot", "Walajah", "Arakkonam", "Sholinghur"],
    "Salem": ["Salem", "Mettur", "Attur", "Omalur", "Edappadi", "Sankari"],
    "Sivaganga": ["Sivaganga", "Karaikudi", "Devakottai", "Manamadurai", "Tiruppattur"],
    "Tenkasi": ["Tenkasi", "Sankarankovil", "Kadayanallur", "Shenkottai", "Puliyangudi"],
    "Thanjavur": ["Thanjavur", "Kumbakonam", "Pattukkottai", "Orathanadu", "Thiruvaiyaru"],
    "Theni": ["Theni", "Periyakulam", "Uthamapalayam", "Cumbum", "Bodinayakanur"],
    "Thoothukudi (Tuticorin)": ["Thoothukudi", "Tiruchendur", "Kovilpatti", "Srivaikuntam", "Ettayapuram"],
    "Tiruchirappalli (Trichy)": ["Tiruchirappalli", "Srirangam", "Lalgudi", "Musiri", "Manapparai", "Thuraiyur"],
    "Tirunelveli": ["Tirunelveli", "Palayamkottai", "Ambasamudram", "Nanguneri", "Radhapuram"],
    "Tirupathur": ["Tirupathur", "Vaniyambadi", "Ambur", "Natrampalli"],
    "Tiruppur": ["Tiruppur", "Avinashi", "Dharapuram", "Udumalaipettai", "Kangeyam", "Palladam"],
    "Tiruvallur": ["Tiruvallur", "Avadi", "Ponneri", "Poonamallee", "Tiruttani", "Gummidipoondi"],
    "Tiruvannamalai": ["Tiruvannamalai", "Arani", "Cheyyar", "Polur", "Chengam", "Wandiwash"],
    "Tiruvarur": ["Tiruvarur", "Mannargudi", "Thiruthuraipoondi", "Nannilam"],
    "Vellore": ["Vellore", "Katpadi", "Gudiyatham", "Anaicut"],
    "Viluppuram": ["Viluppuram", "Tindivanam", "Gingee", "Vanur", "Vikravandi"],
    "Virudhunagar": ["Virudhunagar", "Sivakasi", "Rajapalayam", "Sathur", "Aruppukkottai"]
  },
  "Telangana": {
    "Adilabad": ["Adilabad", "Utnoor", "Boath", "Ichoda", "Bela"],
    "Bhadradri Kothagudem": ["Kothagudem", "Bhadrachalam", "Palwancha", "Yellandu", "Manuguru"],
    "Hanamkonda": ["Hanamkonda", "Kazipet", "Hasanparthy", "Elkathurthy"],
    "Hyderabad": ["Charminar", "Secunderabad", "Khairatabad", "Ameerpet", "Banjara Hills", "Jubilee Hills", "Gachibowli"],
    "Jagtial": ["Jagtial", "Korutla", "Metpally", "Dharmapuri"],
    "Jangaon": ["Jangaon", "Station Ghanpur", "Palakurthi", "Bachannapet"],
    "Jayashankar Bhupalpally": ["Bhupalpally", "Kataram", "Mahadevpur", "Tekumatla"],
    "Jogulamba Gadwal": ["Gadwal", "Alampur", "Ieeja", "Itikyal"],
    "Kamareddy": ["Kamareddy", "Yellareddy", "Banswada", "Jukkal"],
    "Karimnagar": ["Karimnagar", "Huzurabad", "Choppadandi", "Manakondur"],
    "Khammam": ["Khammam", "Wyra", "Sathupally", "Madhira", "Kalluru"],
    "Kumuram Bheem Asifabad": ["Asifabad", "Kagaznagar", "Sirpur", "Rebbena"],
    "Mahabubabad": ["Mahabubabad", "Thorrur", "Dornakal", "Maripeda"],
    "Mahabubnagar": ["Mahabubnagar", "Jadcherla", "Devarkadra", "Badepalle"],
    "Mancherial": ["Mancherial", "Bellampalle", "Mandamarri", "Chennur", "Luxettipet"],
    "Medak": ["Medak", "Toopran", "Ramayampet", "Narsapur"],
    "Medchal-Malkajgiri": ["Malkajgiri", "Kukatpally", "Quthbullapur", "Uppal", "Medchal", "Alwal"],
    "Mulugu": ["Mulugu", "Eturnagaram", "Venkatapur", "Tadvai"],
    "Nagarkurnool": ["Nagarkurnool", "Achampet", "Kalwakurthy", "Kollapur"],
    "Nalgonda": ["Nalgonda", "Miryalaguda", "Devarakonda", "Nakarakal"],
    "Narayanpet": ["Narayanpet", "Makthal", "Kosgi", "Damaragidda"],
    "Nirmal": ["Nirmal", "Bhainsa", "Khanapur", "Mudhole"],
    "Nizamabad": ["Nizamabad", "Armoor", "Bodhan", "Balkonda"],
    "Peddapalli": ["Peddapalli", "Ramagundam", "Manthani", "Godavarikhani"],
    "Rajanna Sircilla": ["Sircilla", "Vemulawada", "Chandurthi"],
    "Ranga Reddy": ["Shamshabad", "Rajendranagar", "Ibrahimpatnam", "Chevella", "Shadnagar", "Hayathnagar"],
    "Sangareddy": ["Sangareddy", "Patancheru", "Zaheerabad", "Narayankhed", "Andole"],
    "Siddipet": ["Siddipet", "Gajwel", "Husnabad", "Dubbak", "Cherial"],
    "Suryapet": ["Suryapet", "Kodad", "Huzurnagar", "Tirumalagiri"],
    "Vikarabad": ["Vikarabad", "Tandur", "Pargi", "Kodangal"],
    "Wanaparthy": ["Wanaparthy", "Pebbair", "Kothakota", "Pangangal"],
    "Warangal": ["Warangal", "Narsampet", "Parkal", "Wardhannapet"],
    "Yadadri Bhuvanagiri": ["Bhongir", "Yadagirigutta", "Choutuppal", "Alair"]
  },
  "Tripura": {
    "Dhalai": ["Ambassa", "Kamalpur", "Gandacherra", "Longtharai Valley"],
    "Gomati": ["Udaipur", "Amarpur", "Karbook"],
    "Khowai": ["Khowai", "Teliamura", "Kalyanpur"],
    "North Tripura": ["Dharmanagar",, "Kailashahar", "Kanchanpur", "Panisagar"],
    "Sepahijala": ["Bishramganj", "Sonamura", "Jatrapur", "Melaghar"],
    "South Tripura": ["Belonia", "Santirbazar", "Sabroom"],
    "Unakoti": ["Kailashahar", "Kumarghat", "Pecharthal"],
    "West Tripura": ["Agartala", "Jirania", "Mohanpur", "Ranirbazar"]
  },
  "Uttar Pradesh": {
    "Agra": ["Etmadpur", "Kheragarh", "Fatehabad", "Pinahat", "Bichpuri", "Fatehpur Sikri", "Shamsabad"],
    "Aligarh": ["Khair", "Iglas", "Atrali", "Ghabhana", "Jawan Sikanderpur", "Lodhha", "Tappal"],
    "Ambedkar Nagar": ["Akbarpur", "Tanda", "Jalalpur", "Alapur", "Bhiti"],
    "Amethi": ["Gauriganj", "Amethi", "Musafirkhana", "Tiloi"],
    "Amroha": ["Amroha", "Gajraula", "Hasanpur", "Dhanaura", "Joyal"],
    "Auraiya": ["Auraiya", "Bidhuna", "Ajitmal"],
    "Ayodhya": ["Ayodhya", "Sohawal", "Milkipur", "Rudauli", "Bikapur", "Pura Bazar", "Masodha"],
    "Azamgarh": ["Azamgarh", "Sagri", "Ghosi Road", "Phulpur Pawai", "Lalganj", "Mehnagar"],
    "Baghpat": ["Baghpat", "Baraut", "Khekra"],
    "Bahraich": ["Bahraich", "Nanpara", "Kaiserganj", "Mahasi", "Payagpur"],
    "Ballia": ["Ballia", "Rasra", "Bansdih", "Bairia", "Belthara Road"],
    "Balrampur": ["Balrampur", "Tulsipur", "Utraula"],
    "Banda": ["Banda", "Atarra", "Baberu", "Naini"],
    "Barabanki": ["Nawabganj", "Fatehpur", "Haidergarh", "Ramsanehi Ghat", "Shedhar"],
    "Bareilly": ["Bareilly", "Faridpur", "Nawabganj", "Baheri", "Aonla", "Meerganj", "Rithora", "Fatehganj"],
    "Basti": ["Basti", "Harraiya", "Bhanpur", "Rudhauli"],
    "Bhadohi": ["Gyanpur", "Bhadohi", "Aurai"],
    "Bijnor": ["Bijnor", "Chandpur", "Dhampur", "Nagina", "Najibabad", "Seohara"],
    "Budaun": ["Budaun", "Sahaswan", "Bilsi", "Dataganj", "Bisauli"],
    "Bulandshahr": ["Bulandshahr", "Khurja", "Sikandrabad", "Siyana", "Anupshahr", "Debai"],
    "Chandauli": ["Chandauli", "Mughalsarai", "Sakaldiha", "Chakia"],
    "Chitrakoot": ["Karwi", "Mau", "Manikpur", "Rajapur"],
    "Deoria": ["Deoria", "Salempur", "Bhatpar Rani", "Rudrapar"],
    "Etah": ["Etah", "Kasganj Road", "Jalesar", "Aliganj"],
    "Etawah": ["Etawah", "Bhartana", "Jaswantnagar", "Saifai"],
    "Farrukhabad": ["Fatehgarh", "Farrukhabad", "Kaimganj", "Amritpur"],
    "Fatehpur": ["Fatehpur", "Bindki", "Khaga"],
    "Firozabad": ["Firozabad", "Shikohabad", "Tundla", "Jasrana"],
    "Gautam Buddha Nagar": ["Noida", "Greater Noida", "Dadri", "Jewar"],
    "Ghaziabad": ["Ghaziabad", "Loni", "Muradnagar", "Modinagar", "Dasna"],
    "Ghazipur": ["Ghazipur", "Zamania", "Mohammadabad", "Saidpur"],
    "Gonda": ["Gonda", "Balrampur Road", "Colonelganj", "Tarabganj", "Mankapur"],
    "Gorakhpur": ["Gorakhpur", "Bansgaon", "Campierganj", "Khajani", "Sahjanwa", "Pipraich"],
    "Hamirpur": ["Hamirpur", "Rath", "Maudaha", "Sarila"],
    "Hapur": ["Hapur", "Garhmukteshwar", "Dhaulana"],
    "Hardoi": ["Hardoi", "Shahabad", "Sandila", "Bilgram", "Sawaizpur"],
    "Hathras": ["Hathras", "Sadabad", "Sikandra Rao", "Sasni"],
    "Jalaun": ["Orai", "Jalaun", "Konch", "Kalpi"],
    "Jaunpur": ["Jaunpur", "Shahganj", "Machhlishahr", "Badlapur", "Kerakat"],
    "Jhansi": ["Jhansi", "Babina", "Moth", "Mauranipur", "Garautha"],
    "Kannauj": ["Kannauj", "Chhibramau", "Tirwa"],
    "Kanpur Dehat": ["Akbarpur", "Rania", "Bhognipur", "Derapur", "Rasoolabad"],
    "Kanpur Nagar": ["Kanpur", "Bidhnoo", "Kalyanpur", "Sarsaul", "Ghatampur", "Bilhaur"],
    "Kasganj": ["Kasganj", "Ganjdundwara", "Patiali"],
    "Kaushambi": ["Manjhanpur", "Sirathu", "Chail"],
    "Kheri (Lakhimpur Kheri)": ["Lakhimpur", "Gola Gokarannath", "Mohammadi", "Palia Kalan", "Nighasan"],
    "Kushinagar": ["Padrauna", "Hata", "Kasya", "Tamkuhi Raj"],
    "Lalitpur": ["Lalitpur", "Mahroni", "Talbehat"],
    "Lucknow": ["Lucknow", "Malihabad", "Bakshi Ka Talab", "Mohanlalganj", "Sarojini Nagar", "Gosainganj"],
    "Maharajganj": ["Maharajganj", "Nautanwa", "Nichlaul", "Pharenda"],
    "Mahoba": ["Mahoba", "Charkhari", "Kulpahar"],
    "Mainpuri": ["Mainpuri", "Bhongaon", "Karhal", "Kishni"],
    "Mathura": ["Mathura", "Vrindavan", "Chhata", "Govardhan", "Raya", "Nandgaon"],
    "Mau": ["Mau", "Ghosi", "Muhammadabad Gohna", "Madhuban"],
    "Meerut": ["Meerut", "Sardhana", "Mawana", "Hastinapur", "Daurala"],
    "Mirzapur": ["Mirzapur", "Chunar", "Vindhyachal", "Lalganj", "Marihan"],
    "Moradabad": ["Moradabad", "Rampur Road", "Sitapur", "Kanth", "Mohanpur", "Bagh Farm", "Kundarki", "Bilari", "Thakurdwara"],
    "Muzaffarnagar": ["Muzaffarnagar", "Khatauli", "Budhana", "Jansath", "Shahpur", "Purkazi"],
    "Pilibhit": ["Pilibhit", "Bisalpur", "Puranpur", "Khatima Road"],
    "Pratapgarh": ["Pratapgarh", "Kunda", "Patti", "Raniganj", "Lalganj"],
    "Prayagraj": ["Prayagraj", "Phulpur", "Handia", "Karchhana", "Bara", "Koraon", "Soraon"],
    "Raebareli": ["Raebareli", "Lalganj", "Bachhrawan", "Salon", "Maharajganj"],
    "Rampur": ["Rampur", "Shahabad", "Milak", "Suar", "Tanda", "Bilaspur"],
    "Saharanpur": ["Saharanpur", "Deoband", "Nakur", "Rampur Maniharan", "Behat", "Gangoh"],
    "Sambhal": ["Sambhal", "Gunnaur", "Asmoli", "Bahjoi", "Chandausi"],
    "Sant Kabir Nagar": ["Khalilabad", "Dhanghata", "Mehdawal"],
    "Shahjahanpur": ["Shahjahanpur", "Tilhar", "Powayan", "Jalalabad"],
    "Shamli": ["Shamli", "Kairana", "Thana Bhawan"],
    "Shravasti": ["Bhinga", "Ikauna"],
    "Siddharthnagar": ["Naugarh", "Bansi", "Domariyaganj", "Shohratgarh", "Itwa"],
    "Sitapur": ["Sitapur", "Biswan", "Maholi", "Misrikh", "Laharpur", "Mahmudabad", "Khairabad"],
    "Sonbhadra": ["Robertsganj", "Renukoot", "Obra", "Duddhi", "Ghorawal"],
    "Sultanpur": ["Sultanpur", "Kadipur", "Lambhua", "Jaisinghpur"],
    "Unnao": ["Unnao", "Shuklaganj", "Hasanganj", "Purwa", "Safipur", "Bangarmau"],
    "Varanasi": ["Varanasi", "Pindra", "Sevapuri", "Arajiline", "Cholapur", "Harahua", "Kashi Vidyapeeth"]
  },
  "Uttarakhand": {
    "Almora": ["Almora", "Ranikhet", "Dwarahat", "Bhikiyasain", "Chaukhutiya", "Someshwar"],
    "Bageshwar": ["Bageshwar", "Kapkot", "Garur"],
    "Chamoli": ["Gopeshwar", "JoshiMath", "Karanprayag", "Gauchar", "Ghat"],
    "Champawat": ["Champawat", "Lohaghat", "Tanakpur", "Pati"],
    "Dehradun": ["Dehradun", "Rishikesh", "Doiwala", "Vikasnagar", "Chakrata", "Kalsi", "Mussoorie"],
    "Haridwar": ["Haridwar", "Roorkee", "Laksar", "Khanpur", "Bhagwanpur"],
    "Nainital": ["Nainital", "Haldwani", "Ramnagar", "Bhowali", "Kaladhungi", "Lalkuan"],
    "Pauri Garhwal": ["Pauri", "Kotdwar", "Srinagar", "Lansdowne", "Rudraprayag Road"],
    "Pithoragarh": ["Pithoragarh", "Didihat", "Dharchula", "Gangolihat", "Berinag"],
    "Rudraprayag": ["Rudraprayag", "Ukhimath", "Jakholi"],
    "Tehri Garhwal": ["New Tehri", "Narendranagar", "Chamba", "Ghansali", "Devprayag"],
    "Udham Singh Nagar": ["Rudrapur", "Kashipur", "Khatima", "Jaspur", "Sitarganj", "Gadarpur", "Kichha"],
    "Uttarkashi": ["Uttarkashi", "Purola", "Barkot", "Bhatwari", "Mori"]
  },
  "West Bengal": {
    "Alipurduar": ["Alipurduar", "Falakata", "Kalchini", "Madarihat", "Kumargram"],
    "Bankura": ["Bankura", "Bishnupur", "Khatra", "Barjora", "Sonamukhi", "Onda"],
    "Birbhum": ["Suri", "Bolpur (Santiniketan)", "Rampurhat", "Sainthia", "Dubrajpur", "Nalhati"],
    "Cooch Behar": ["Cooch Behar", "Dinhata", "Mathabhanga", "Tufanganj", "Mekhliganj"],
    "Dakshin Dinajpur": ["Balurghat", "Gangarampur", "Buniadpur", "Kumarganj", "Harirampur"],
    "Darjeeling": ["Darjeeling", "Siliguri", "Kurseong", "Mirik"],
    "Hooghly": ["Chinsurah", "Chandannagar", "Serampore", "Singur", "Tarakeswar", "Arambagh"],
    "Howrah": ["Howrah", "Bally", "Uluberia", "Bagnan", "Amta", "Domjur"],
    "Jalpaiguri": ["Jalpaiguri", "Dhupguri", "Malbazar", "Maynaguri"],
    "Jhargram": ["Jhargram", "Gopiballavpur", "Nayagram", "Binpur", "Belpahari"],
    "Kalimpong": ["Kalimpong", "Gorubathan", "Pedong"],
    "Kolkata": ["Kolkata", "Park Street", "Salt Lake", "New Town", "Alipore", "Bhowanipore", "Jadavpur"],
    "Malda": ["English Bazar (Malda)", "Old Malda", "Gazole", "Chanchal", "Kaliachak", "Ratua"],
    "Murshidabad": ["Berhampore", "Lalgola", "Kandi", "Jangipur", "Domkal", "Beldanga"],
    "Nadia": ["Krishnanagar", "Ranaghat", "Kalyani", "Tehatta", "Chakdaha", "Santipur"],
    "North 24 Parganas": ["Barasat", "Barrackpore", "Bidhannagar", "Basirhat", "Bongaon", "Habra"],
    "Paschim Bardhaman": ["Asansol", "Durgapur", "Raniganj", "Kulti", "Jamuria"],
    "Paschim Medinipur": ["Midnapore", "Kharagpur", "Ghatal", "Garhbeta", "Debra"],
    "Purba Bardhaman": ["Bardhaman", "Kalna", "Katwa", "Memari", "Galsi"],
    "Purba Medinipur": ["Tamluk", "Haldia", "Contai", "Digha", "Egra", "Nandigram"],
    "Purulia": ["Purulia", "Raghunathpur", "Jhalda", "Manbazar", "Balarampur"],
    "South 24 Parganas": ["Alipore", "Baruipur", "Canning", "Diamond Harbour", "Kakdwip", "Sonarpur"],
    "Uttar Dinajpur": ["Raiganj", "Islampur", "Kaliaganj", "Karandighi", "Dalkhola"]
  },

  // --- 8 UNION TERRITORIES ---
  "Andaman and Nicobar Islands": {
    "Nicobar": ["Car Nicobar", "Nancowry", "Great Nicobar (Campbell Bay)"],
    "North and Middle Andaman": ["Mayabunder", "Diglipur", "Rangat"],
    "South Andaman": ["Port Blair", "Ferrargunj", "Little Andaman (Hut Bay)"]
  },
  "Chandigarh": {
    "Chandigarh": ["Sector 17", "Manimajra", "Industrial Area", "Sector 35", "Dhanas", "Behlana"]
  },
  "Dadra and Nagar Haveli and Daman and Diu": {
    "Dadra and Nagar Haveli": ["Silvassa", "Khanvel", "Rakholi", "Dadra"],
    "Daman": ["Daman", "Nani Daman", "Moti Daman"],
    "Diu": ["Diu", "Fudam", "Bucharwada", "Ghoghla"]
  },
  "Delhi (NCT of Delhi)": {
    "Central Delhi": ["Connaught Place", "Karol Bagh", "Paharganj", "Daryaganj"],
    "East Delhi": ["Preet Vihar", "Mayur Vihar", "Shahdara", "Laxmi Nagar", "Gandhi Nagar"],
    "New Delhi": ["Chanakyapuri", "Vasant Vihar", "Delhi Cantt", "RK Puram"],
    "North Delhi": ["Civil Lines", "Sadar Bazar", "Kotwali", "Timarpur"],
    "North East Delhi": ["Seelampur", "Yamuna Vihar", "Karawal Nagar", "Shahdara"],
    "North West Delhi": ["Rohini", "Kanjhawala", "Narela", "Model Town"],
    "Shahdara": ["Shahdara", "Seemapuri", "Vivek Vihar"],
    "South Delhi": ["Saket", "Hauz Khas", "Mehrauli", "Greater Kailash", "Green Park"],
    "South East Delhi": ["Defence Colony", "Kalkaji", "Sarita Vihar", "Okhla"],
    "South West Delhi": ["Dwarka", "Najafgarh", "Vasant Kunj", "Palam"],
    "West Delhi": ["Rajouri Garden", "Punjabi Bagh", "Janakpuri", "Patel Nagar"]
  },
  "Jammu and Kashmir": {
    "Anantnag": ["Anantnag", "Bijbehara", "Pahalgam", "Dooru", "Kokernag"],
    "Bandipora": ["Bandipora", "Gurez", "Sumbal"],
    "Baramulla": ["Baramulla", "Sopore", "Gulmarg", "Pattan", "Uri"],
    "Budgam": ["Budgam", "Beerwah", "Chadoora", "Magam"],
    "Doda": ["Doda", "Bhaderwah", "Gandoh", "Thathri"],
    "Ganderbal": ["Ganderbal", "Kangan", "Tullamulla"],
    "Jammu": ["Jammu", "RS Pura", "Akhnoor", "Bishnah", "Nagrota"],
    "Kathua": ["Kathua", "Hiranagar", "Basohli", "Billawar"],
    "Kishtwar": ["Kishtwar", "Paddar", "Marwah", "Chhatroo"],
    "Kulgam": ["Kulgam", "Devsar", "Dharmora", "Yaripora"],
    "Kupwara": ["Kupwara", "Handwara", "Karnah", "Lolab"],
    "Poonch": ["Poonch", "Mendhar", "Surankote", "Mandi"],
    "Pulwama": ["Pulwama", "Pampore", "Tral", "Awantipora"],
    "Rajouri": ["Rajouri", "Nowshera", "Sunderbani", "Budhal"],
    "Ramban": ["Ramban", "Banihal", "Batote", "Gool"],
    "Reasi": ["Reasi", "Katara", "Mahore", "Pouni"],
    "Samba": ["Samba", "Vijaypur", "Ramgarh"],
    "Shopian": ["Shopian", "Zainapora", "Keller"],
    "Srinagar": ["Srinagar", "Hazratbal", "Khanyar", "Sonwar", "Rainawari"],
    "Udhampur": ["Udhampur", "Ramnagar", "Chenani", "Majalta"]
  },
  "Ladakh": {
    "Kargil": ["Kargil", "Zanskar", "Dass", "Sankoo", "Shakar Chiktan"],
    "Leh": ["Leh", "Nubra", "Khaltse", "Nyoma", "Diskit", "Pangong Tso"]
  },
  "Lakshadweep": {
    "Lakshadweep": ["Kavaratti", "Agatti", "Amini", "Andrott", "Kadmat", "Kalpeni", "Minicoy"]
  },
  "Puducherry": {
    "Karaikal": ["Karaikal", "Kottucherry", "Nedungadu", "Thirunallar"],
    "Mahe": ["Mahe", "Pandakkal", "East Palloor"],
    "Puducherry": ["Puducherry", "Ozhukarai", "Ariyankuppam", "Villianur", "Bahour"],
    "Yanam": ["Yanam", "Guriempeta", "Savithri Nagar"]
  }
};

async function seed() {
  try {
    await mongoose.connect(MONGODB_URI, {
      serverSelectionTimeoutMS: 15000,
      connectTimeoutMS: 15000
    });

    console.log('✅ Connected to MongoDB Atlas for seeding locations...');

    const stateKeys = Object.keys(INDIA_ADMINISTRATIVE_DATA);
    let totalDistrictsCount = 0;
    let totalVillagesCount = 0;

    const bulkOps = [];

    for (const stateName of stateKeys) {
      const districtsObj = INDIA_ADMINISTRATIVE_DATA[stateName];
      const districtNames = Object.keys(districtsObj);
      totalDistrictsCount += districtNames.length;

      for (const distName of districtNames) {
        const villagesList = districtsObj[distName];
        totalVillagesCount += villagesList.length;

        for (const villageName of villagesList) {
          bulkOps.push({
            updateOne: {
              filter: { state: stateName, district: distName, village: villageName },
              update: {
                $set: {
                  state: stateName,
                  district: distName,
                  village: villageName
                }
              },
              upsert: true
            }
          });
        }
      }
    }

    console.log(`📦 Preparing bulk update of ${bulkOps.length} location records...`);
    
    // Process in batches of 500
    const batchSize = 500;
    for (let i = 0; i < bulkOps.length; i += batchSize) {
      const batch = bulkOps.slice(i, i + batchSize);
      await Location.bulkWrite(batch);
    }

    const dbStates = await Location.distinct('state');
    const dbDistricts = await Location.distinct('district');
    const dbVillagesCount = await Location.countDocuments({});

    // Verify existing mills collection is untouched
    const millsCollection = mongoose.connection.db.collection('mills');
    const millsCount = await millsCollection.countDocuments({});

    const summary = {
      status: 'success',
      statesCount: dbStates.length,
      districtsCount: dbDistricts.length,
      villagesCount: dbVillagesCount,
      millsCountIntact: millsCount,
      sampleStates: dbStates.slice(0, 10)
    };

    console.log(JSON.stringify(summary, null, 2));

    await mongoose.disconnect();
  } catch (err) {
    console.log(JSON.stringify({ status: 'error', error: err.message }, null, 2));
    if (mongoose.connection.readyState !== 0) {
      await mongoose.disconnect().catch(() => {});
    }
    process.exit(1);
  }
}

seed();
